name: ci

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/scrin/siikabot
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/scrin/siikabot:${{ matrix.arch }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  create-manifest:
    name: Create and push manifest
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest
        run: |
          docker manifest create ghcr.io/scrin/siikabot:latest \
            ghcr.io/scrin/siikabot:amd64-${{ github.sha }} \
            ghcr.io/scrin/siikabot:arm64-${{ github.sha }}
          
          docker manifest create ghcr.io/scrin/siikabot:${{ github.sha }} \
            ghcr.io/scrin/siikabot:amd64-${{ github.sha }} \
            ghcr.io/scrin/siikabot:arm64-${{ github.sha }}
      - name: Push manifest
        run: |
          docker manifest push ghcr.io/scrin/siikabot:latest
          docker manifest push ghcr.io/scrin/siikabot:${{ github.sha }}
