name: ci

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    name: Build on ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    outputs:
      amd64-digest: ${{ steps.set-output.outputs.amd64-digest }}
      arm64-digest: ${{ steps.set-output.outputs.arm64-digest }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/scrin/siikabot
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/scrin/siikabot:${{ matrix.arch }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=ghcr.io/scrin/siikabot:${{ matrix.arch }}-${{ github.sha }},push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        id: digest
        run: |
          echo "DIGEST=$(docker buildx imagetools inspect ghcr.io/scrin/siikabot:${{ matrix.arch }}-${{ github.sha }} --format '{{json .}}' | jq -r '.manifest.digest')" >> $GITHUB_OUTPUT
      - name: Store digest in step summary
        run: |
          echo "${{ matrix.arch }}=${{ steps.digest.outputs.DIGEST }}" >> $GITHUB_STEP_SUMMARY
      - name: Set job output
        id: set-output
        if: matrix.arch == 'amd64'
        run: echo "amd64-digest=${{ steps.digest.outputs.DIGEST }}" >> $GITHUB_OUTPUT
      - name: Set job output
        if: matrix.arch == 'arm64'
        run: echo "arm64-digest=${{ steps.digest.outputs.DIGEST }}" >> $GITHUB_OUTPUT

  create-manifest:
    name: Create and push manifest
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest
        run: |
          # Get digests from job outputs
          AMD64_DIGEST="${{ needs.docker-build.outputs.amd64-digest }}"
          ARM64_DIGEST="${{ needs.docker-build.outputs.arm64-digest }}"
          
          echo "Using AMD64 digest: $AMD64_DIGEST"
          echo "Using ARM64 digest: $ARM64_DIGEST"
          
          # Create and push the 'latest' manifest
          docker buildx imagetools create -t ghcr.io/scrin/siikabot:latest \
            ghcr.io/scrin/siikabot@$AMD64_DIGEST \
            ghcr.io/scrin/siikabot@$ARM64_DIGEST
          
          # Create and push the SHA manifest
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker buildx imagetools create -t ghcr.io/scrin/siikabot:$SHORT_SHA \
            ghcr.io/scrin/siikabot@$AMD64_DIGEST \
            ghcr.io/scrin/siikabot@$ARM64_DIGEST
