name: ci

on:
  push:
    branches:
      - master

jobs:
  docker-build-amd64:
    name: Build AMD64 image
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          outputs: type=image,name=ghcr.io/scrin/siikabot,push-by-digest=true,name-canonical=true,push=true
          labels: ${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Get digest
        id: digest
        run: |
          DIGEST="${{ steps.docker_build.outputs.digest }}"
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "AMD64 Digest: $DIGEST"
      - name: Store digest in step summary
        run: |
          echo "amd64=${{ steps.digest.outputs.digest }}" >> $GITHUB_STEP_SUMMARY

  docker-build-arm64:
    name: Build ARM64 image
    runs-on: ubuntu-24.04-arm
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          outputs: type=image,name=ghcr.io/scrin/siikabot,push-by-digest=true,name-canonical=true,push=true
          labels: ${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Get digest
        id: digest
        run: |
          DIGEST="${{ steps.docker_build.outputs.digest }}"
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "ARM64 Digest: $DIGEST"
      - name: Store digest in step summary
        run: |
          echo "arm64=${{ steps.digest.outputs.digest }}" >> $GITHUB_STEP_SUMMARY

  create-manifest:
    name: Create and push manifest
    needs: [docker-build-amd64, docker-build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest
        run: |
          # Get digests from job outputs
          AMD64_DIGEST="${{ needs.docker-build-amd64.outputs.digest }}"
          ARM64_DIGEST="${{ needs.docker-build-arm64.outputs.digest }}"
          
          echo "Using AMD64 digest: $AMD64_DIGEST"
          echo "Using ARM64 digest: $ARM64_DIGEST"
          
          # Create and push the 'latest' manifest
          docker buildx imagetools create -t ghcr.io/scrin/siikabot:latest \
            ghcr.io/scrin/siikabot@$AMD64_DIGEST \
            ghcr.io/scrin/siikabot@$ARM64_DIGEST
          
          # Create and push the SHA manifest
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker buildx imagetools create -t ghcr.io/scrin/siikabot:$SHORT_SHA \
            ghcr.io/scrin/siikabot@$AMD64_DIGEST \
            ghcr.io/scrin/siikabot@$ARM64_DIGEST
